# ----------------------------------------------------------------------------------------------------------------------
# Commands

# Donate: Provides a target x amount of health, subtracting x health from the user.
# - All players can use this command by default.
donate-command: true
# Health: Returns, adds to, removes from, or sets the target user's health.
# - Only OP users can use this command by default.
health-command: true
# Revive: Makes an eliminated target alive and provides them with x amount of health if provided.
# - Only OP users can use this command by default.
revive-command: true
# Withdraw: Takes one heart from the user and converts it to an item that can be used to get it back.
# - All players can use this command by default.
withdrawal-command: true

# ----------------------------------------------------------------------------------------------------------------------
# Events

# If disabled, players will not automatically gain health upon killing another player.
# Instead, players will drop a heart upon death by another player that can be used.
# Enabled by default.
automatic-health: true
# If enabled, hearts will be allowed inside of ender chests.
# Disabled by default to prevent inaccessible items in raids/battles.
allow-ender-hearts: false
# Determines the punishment given to eliminated players.
# - "banned" = Bans and kicks the eliminated player. Default.
# - "hardcore" = Bans the eliminated player, but does not kick them, rather putting them into spectator mode.
# - "spectator" = Puts the eliminated player into spectator mode without banning them.
elimination-type: 'banned'

#-----------------------------------------------------------------------------------------------------------------------
# Items and Recipes
# Determines the crafting method for hearts.
# - "fragment-#" = Shapeless recipe that requires # fragments to craft, whereas # is a number between 1 and 9.
#    - If a number is not provided, the recipe defaults to 4 fragments to craft.
# - "smp" = Mimics the recipe from a certain popular SMP.
# - "custom-shaped" = Custom shaped recipe. To be implemented eventually.
# - "custom-shapeless" = Custom shapeless recipe. To be implemented eventually.
# - "none" = Hearts are unavailable to craft. Default.
heart-crafting: 'none'

custom:
  # If true, permits the use of heart fragments in a custom recipe.
  # Otherwise, the recipe will not work if heart fragments are used.
  uses-heart-fragments: false
  type: 'shaped'
#     List of recipe values (enums) available at https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
#     Example: Diamond Pickaxe Recipe
#     - DIAMOND DIAMOND DIAMOND
#     - AIR STICK AIR
#     - AIR STICK AIR
#     If uses-heart-fragments is true, use "HEART_FRAGMENT" to specify a heart fragment.
  shaped:
    - AIR AIR AIR
    - AIR AIR AIR
    - AIR AIR AIR

